mvcHaber/Controllers/AdminHaberController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using mvcHaber.Models;
using PagedList;
using PagedList.Mvc;

namespace mvcHaber.Controllers
{
    public class AdminHaberController : Controller
    {
        mvchaberDB db = new mvchaberDB();
        // GET: AdminHaber
        public ActionResult Index(int page=1)
        {
            var habers = db.Makales.OrderByDescending(m=>m.MakaleId).ToPagedList(page,10);
            return View(habers);
        }

        // GET: AdminHaber/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdminHaber/Create
        public ActionResult Create()
        {
            ViewBag.KategoriId = new SelectList(db.Kategoris, "KategoriId", "KategoriAd");
            return View();
        }

        // POST: AdminHaber/Create
        [HttpPost]
        public ActionResult Create(Makale makale, string etiketler, HttpPostedFileBase Foto)
        {
            if (ModelState.IsValid)
            {
                if (Foto != null)
                {
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                    makale.Foto = "/Uploads/MakaleFoto/" + newfoto;


                }
                if (etiketler != null)
                {
                    string[] etiketdizi = etiketler.Split(',');
                    foreach (var i in etiketdizi)
                    {
                        var yenietiket = new Etiket { EtiketAdi = i };
                        db.Etikets.Add(yenietiket);
                        makale.Etikets.Add(yenietiket);
                    }
                }

                makale.UyeId = Convert.ToInt32(Session["uyeid"]);
                makale.Okunma = 1; // 1 yapmamızın sebibi eğer null olursa arttırım gerçekleşmiyor.
                db.Makales.Add(makale);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(makale);

        }

        // GET: AdminHaber/Edit/5
        public ActionResult Edit(int id)
        {
            var makale = db.Makales.Where(m => m.MakaleId == id).SingleOrDefault();
            if (makale == null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriId = new SelectList(db.Kategoris, "KategoriId", "KategoriAd", makale.KategoriId);
            return View(makale);
        }

        // POST: AdminHaber/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, HttpPostedFileBase Foto, Makale makale)
        {
            try
            {
                var makales = db.Makales.Where(m => m.MakaleId == id).SingleOrDefault();

                if (Foto != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(makales.Foto)))
                    {
                        System.IO.File.Delete(Server.MapPath(makales.Foto));
                    }
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                    makales.Foto = "/Uploads/MakaleFoto/" + newfoto;
                    makales.Baslik = makale.Baslik;
                    makales.Icerik = makale.Icerik;
                    makales.KategoriId = makale.KategoriId;

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
               
                return View();

            }
            catch
            {
                ViewBag.KategoriId = new SelectList(db.Kategoris, "KategoriId", "KategoriAdi", makale.KategoriId);
                return View(makale);
            }
        }

        // GET: AdminHaber/Delete/5
        public ActionResult Delete(int id) //İndex sayfasındaki sil butonundan id geliyor
        {
            //Bu makalenin makale id si bize dışarıdan gelen id dir diyoruz.
            var makale = db.Makales.Where(m => m.MakaleId == id).SingleOrDefault();
            if (makale == null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        // POST: AdminHaber/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var makales = db.Makales.Where(m => m.MakaleId == id).SingleOrDefault();
                if (makales == null)
                {
                    return HttpNotFound();
                }
                if (System.IO.File.Exists(Server.MapPath(makales.Foto)))
                {
                    System.IO.File.Delete(Server.MapPath(makales.Foto));
                }
                foreach (var i in makales.Yorums.ToList())
                {
                    db.Yorums.Remove(i);
                }
                foreach (var i in makales.Etikets.ToList())
                {
                    db.Etikets.Remove(i);
                }
                db.Makales.Remove(makales);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

mvcHaber/Views/AdminHaber/Create.cshtml
@model mvcHaber.Models.Makale

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Haber Oluşturma Sayfası</h2>

@using (Html.BeginForm("Create", "AdminHaber", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
   
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.KategoriId, "KategoriId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("KategoriId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Foto" id="Foto" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
            @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Etiketler", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("Etiketler")
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

mvcHaber/Views/AdminHaber/Delete.cshtml
@model mvcHaber.Models.Makale

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Haber Silme Sayfası</h2>

<h3>Silmeyi Onaylıyor Musunuz?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Icerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icerik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            <img src="@Model.Foto" width="150" alt="Alternate Text" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UyeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UyeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Okunma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Okunma)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

mvcHaber/Views/AdminHaber/Edit.cshtml
@model mvcHaber.Models.Makale

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Haber Düzenleme Sayfası</h2>

@using (Html.BeginForm("Edit", "AdminHaber", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MakaleId)

    <div class="form-group">
        @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Eski Foto", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <img width="75" src="@Model.Foto" alt="Alternate Text" />
            @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Foto" id="Foto" value="" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
            @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KategoriId, "KategoriId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("KategoriId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

mvcHaber/Views/AdminHaber/Index.cshtml
@model IPagedList<mvcHaber.Models.Makale>
@using PagedList
@using PagedList.Mvc
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}
<h2>Haberler</h2>
<p>
    @Html.ActionLink("Yeni Haber Oluştur", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.Label("Kategori Adı")

        </th>
        <th>
            @Html.Label("Başlık")

        </th>
        <th>
            @Html.Label("Foto")

        </th>

        <th>
            @Html.Label("Tarih")
        </th>

        <th>
            @Html.Label("Okunma Sayısı")

        </th>
        <th>
        </th>


    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Kategori.KategoriAd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Baslik)
            </td>

            <td>
                <img width="75" src="@item.Foto" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tarih)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Okunma)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MakaleId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MakaleId })
            </td>
        </tr>
    }

</table>
<div class="pagination">
    <nav>
        <ul>
            @Html.PagedListPager(Model, Page => Url.Action("Index", new { Page }), PagedListRenderOptions.Classic);
        </ul>
    </nav>
</div>